### ISSUE TITLE
Repo meta data

### ISSUE THREAD

**Issue by bdougie** [open-sauced/open-sauced#384]
At the moment start and contributors props are being hardcoded. This should be dynamically added to the repo list. 

https://github.com/bdougie/open-sauced/blob/master/src/components/ListGoals.js#L21

## problem

The data is currently not being collected via the GraphQL API. An update to the way the data is being fetched and stored should happed. 

## proposal

Instead of only storing general notes, the body of the issue should store an object to store a few different things. 

Example current issue body stores free form notes: `This is a note`

Proposed example:
```
{
  notes: this is a note,
  nameWithOwner: "primer/components"
  owner: "primer",
  repoName: "components",
  contributions: [
    "https://github.com/primer/components/issues/513",
    "https://github.com/primer/components/issues/514",
  ]   
}
```

**Comment by bdougie** [comment]
Path moving forward. 

- [ ] Create open-sauced-goals template
- [ ] Create a README in that template explaining how the goals repo works. 
- [ ] Switch the createGoals mutation to create from a template. 
- [ ] Create GitHub action that creates a file in the open-sauced-goals repo when an issue is opened. Add to the template.

When creating goals, create a folder structure that matches owner/repoName/repo.json

**Comment by bdougie** [comment]
I have a working that needs some polish. 

I am on the fence if the Action should push directly to master or not. 

https://github.com/notBdougie/open-sauced-goals/blob/master/.github/workflows/sauce-grab.yml

**Comment by bdougie** [comment]
Update: I have the solution working but have not implemented it yet, due to my time being constrained. 

I am going to limit the scope to only provide star and topic data. I won't get to it until this weekend, but it will get done. 

![Screenshot 2020-05-28 06 22 17](https://user-images.githubusercontent.com/5713670/83146778-9a7daa00-a0ab-11ea-8d83-dd9f79347c85.png)

**Comment by bdougie** [comment]
The goals-template has been updated to create structured goals data.json to unblocked this work. Some things that still need to be addressed. 

- [ ] Need a way to update existing user repos. [sync-2-upstream](https://github.com/open-sauced/goals-template/blob/master/.github/workflows/sync-2-upstream.yml) will hopefully work with new users, but we will need to check for the existence of this file in current user repos and create a feature to add the file through the app.
- [ ] Move logic for the goals caching action should be moved into the one action [open-sauced/goals-caching](https://github.com/open-sauced/goals-caching).
- [ ] Leverage GraphQL to properly filter closed issues from the fetching.
- [ ] Address the duplicate repo bug #555 

Example of the data can be found at [bdougie/open-sauced-goals/data.json](https://github.com/bdougie/open-sauced-goals/blob/master/data.json)

**Comment by yg** [comment]
@bdougie So it will not be realtime?

**Comment by bdougie** [comment]
No, it won't be realtime, the first-page load should be this data, we can add an action to trigger an update using the [repository_dispatch](https://developer.github.com/v3/repos/#create-a-repository-dispatch-event)

**Comment by yg** [comment]
@bdougie Triggering updates using both cron scheduler and trigger button in UI?

**Comment by bdougie** [comment]
Yep, a button or event would work. 

Also data fetching will look like this.

```
query dataJson {
  gitHub {
    repository(
      name: "open-sauced-goals"
      owner: "bdougie"
    ) {
      id
      owner {
        id
      }
      object(expression: "master:data.json") {
        id
        ... on GitHubBlob {
          id
          text
          commitUrl
        }
      }
    }
  }
}

```

**Comment by bdougie** [comment]
I am going to leave this issue open even after the 0.15.0 release. 

We still need a way to sync users' open-sauced-goals repo with he [goals-template](https://github.com/open-sauced/goals-template). 

My thought is instead of using forkbacon to rebase, it should do a force merge to wipe out the previous history. This is mainly because the history in the repo does not matter as much. The issue is what is needed. 

- look into contributing to forkbacon to add a force merge feature.
- add a notification and/or button in the UI to force commit history to align with the goals-template.

**Comment by bdougie** [comment]
Forkbacon has been implemented. The next step is leveraging the VERSION file and allowing force syncing when the user's version is out of sync.

**Comment by bdougie** [comment]
Closing since https://github.com/open-sauced/open-sauced/issues/667 exists to work on the last open-ended item.
