### ISSUE TITLE
Open Sauced Migration Checklist

### ISSUE THREAD

**Issue by yg** [open-sauced/open-sauced#567]
# Open Sauced Migration Checklist

## Pre Transfer

- [x] Change Repository Links in
  - [x] Websites Linked @bdougie  
  - [x] README (mainly badges) @yg 
  - [x] CONTRIBUTING (mainly badges) @yg 
- [x] LICENSE change to org name
  - [x] LICENCE file @yg 
  - [x] README @yg 
- [x] Remove unused [projects](https://github.com/bdougie/open-sauced/projects) @bdougie 
- [x] Remove unwanted [issue labels](https://github.com/bdougie/open-sauced/labels) and standardize it  @yg 
- [x] Backup entire repo locally @yg, @bdougie 
- [x] Transfer the repo @bdougie 

## Post Transfer

- [x] Change Netlify Repo Path @bdougie 
  - [x] Check it is building correctly without issues @bdougie 
- [x] Check Discord Webhook  @yg, @bdougie 
- [x] Check All issues, PR and discussions has been transferred  @yg, @bdougie 
- [x] Check **logs4netlify** is working  @yg, @bdougie 
- [x] Remap Dependabot Preview Integration @bdougie 
- [ ] Add necessary integration
  - [ ] Imgbot (still in [discussion](https://github.com/bdougie/open-sauced/discussions/560)) @bdougie 

## Local

- [x] Change git remote URL  @yg, @bdougie 
- [x] Run git fetch  @yg, @bdougie

**Comment by bdougie** [comment]
Not sure if this is necessary, but there is an action that checks for broken links as part of CI. https://github.com/marketplace/actions/broken-link-check

**Comment by yg** [comment]
@bdougie Wheather we are going to use **logs4netlify**?, it creates lot of deployments, Netlify itself has auto-deploy for PRs!

WDYT?

**Comment by bdougie** [comment]
The value with logs4netlify is that it gives you https://github.com/bdougie/open-sauced/deployments. This is not duplicate effort but another place to link to netlify and keep of things without me giving access directly to my netlify account.  

I think the easy solution having the deploy inactivated on github when the PR is merged.
